/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package goodreads;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {


    @Test public void testReverse() {
        int[] even = {10, 20, 30, 40};

        assertNotNull("app should have a greeting","app should have a greeting");
    }
}
